### ISSUE TITLE
109360226_陳冠霖

### ISSUE THREAD

**Issue by leochen369** [taipeitechmmslab/Issue-italkutalk#3]
![Screenshot_20200926-111943_iTalkuTalk](https://user-images.githubusercontent.com/71515490/94329108-8a8abe00-ffea-11ea-8d3a-497f248b1948.jpg)

## 回報者信箱
10612224@gm.ptivs.tn.edu.tw

## 使用的設備
 - 手機廠商: samsung
 - 手機型號: GalaxyA7(2018)	
 - 作業系統: android	
 - 應用程式版本: 10

## 遇到的問題	
請在此描述使用什麼功能，遇到怎樣的問題
ex：無

## 問題如何產生	
請在此說明問題發生時，您使用的步驟	
1. 在觀看影片的頁面	
2. 點擊 AI 發音練習按鈕	
3. 練習完畢後，顯示的準確率有錯誤

## 螢幕截圖	
請提供螢幕截圖，以利我們協助您排除問題 (將圖片拖曳至此處即自動上傳)

**Comment by ben111497** [comment]
@leochen369 請附上螢幕截圖。
