### ISSUE TITLE
107360139 吳瑞復

### ISSUE THREAD

**Issue by WUJUIFU** [taipeitechmmslab/Issue-italkutalk#62]
## 許願者信箱
eric9881285@gmail.com

手機廠商: Apple
手機型號: iPhone8
作業系統: iOS13.5.1
應用程式版本: 2.0.37

## 期望功能
1.希望上排(我的單字 我的字典 記憶練習 聽力練習)能夠完全顯示
2.下排功能列當中的"更多" 在此選單上下滑動的時候特別難滑 需要在特定位置才能滑動
3.希望影片能夠有快轉及倒退的功能

**Comment by chenchewei** [comment]
@WUJUIFU 同學你好，能否請你提供第一點的截圖呢？
